version: '3.8'

services:
  # vendor-db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: "myproject"
  #     POSTGRES_USER: "db_user"
  #     POSTGRES_PASSWORD: "password"
  #   networks:
  #     - vendor-network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # depends_on:
    #   - vendor-db
    # environment:
    #   DATABASE_URL: postgres://myprojectuser:password@db/myproject
    networks:
      - vendor-network

# volumes:
#   postgres_data:

networks:
  vendor-network:
    driver: bridge
